# Generated by Django 3.2.6 on 2021-08-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='zip_file_name',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='music_file',
            field=models.FileField(upload_to=''),
        ),
    ]
