# Generated by Django 3.2.6 on 2021-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210803_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfiles',
            name='zip_file_name',
        ),
    ]
