# Generated by Django 3.2.6 on 2021-08-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210803_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipfilename',
            old_name='name',
            new_name='zip_file_name',
        ),
    ]
