# Generated by Django 3.2.6 on 2021-08-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_zipfilename_zip_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabFileText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crontab_text', models.TextField(max_length=20000)),
            ],
        ),
    ]
